import fs from 'fs';
import fsp from 'fs/promises';
import path from 'path';

export const command = 'llm-bridge <provider> [folder name]';
export const describe = 'Scaffold a local LLM bridge into .vmblu/llm-bridge for a vmblu app';
export const builder = [
  { flag: '--origin <url>', desc: 'Allowed frontend origin (default: http://localhost:5173, or use "any")' },
  { flag: '--port <number>', desc: 'Local port for the bridge (default: 8080)' },
  { flag: '--force', desc: 'Overwrite existing files' },
  { flag: '--dry-run', desc: 'Show actions without writing' }
];

export const handler = async (argv) => {
  const args = parseCliArgs(argv);
  const provider = String(args._[0] || '').toLowerCase();
  const targetDir = path.resolve(args._[1] || '.');
  const force = Boolean(args.force);
  const dryRun = Boolean(args.dryRun);
  const port = parsePort(args.port);
  const origin = args.origin || 'http://localhost:5173';

  if (!provider) {
    printUsage();
    process.exit(1);
  }

  if (provider !== 'openai') {
    throw new Error(`Unsupported provider "${provider}". Supported providers: openai`);
  }

  const vmbluDir = path.join(targetDir, '.vmblu');
  if (!fs.existsSync(vmbluDir) || !fs.statSync(vmbluDir).isDirectory()) {
    throw new Error(`Target is not a vmblu project (missing ${vmbluDir}). Run "vmblu init" first.`);
  }

  const bridgeDir = path.join(vmbluDir, 'llm-bridge');
  const config = buildConfig({ provider, origin, port });
  const files = [
    { path: path.join(bridgeDir, 'config.json'), content: JSON.stringify(config, null, 2) + '\n' },
    { path: path.join(bridgeDir, 'proxy.js'), content: buildProxySource() },
    { path: path.join(bridgeDir, 'README.md'), content: buildReadme({ provider, origin }) }
  ];

  for (const file of files) {
    await ensureDir(path.dirname(file.path), dryRun);
    await writeFileSafe(file.path, file.content, { force, dryRun });
  }

  await addPackageScript(targetDir, { force, dryRun });

  if (origin === 'any') {
    console.warn('The generated bridge allows any browser origin. This is convenient for local testing, but less safe than a single explicit origin.');
  }

  console.log(`LLM bridge scaffolded in ${bridgeDir}`);
};

function parseCliArgs(argvInput) {
  const argv = Array.isArray(argvInput) ? argvInput : [];
  const result = { _: [] };

  for (let i = 0; i < argv.length; i++) {
    const token = argv[i];
    if (token === '--force') {
      result.force = true;
      continue;
    }
    if (token === '--dry-run') {
      result.dryRun = true;
      continue;
    }
    if (token === '--origin') {
      result.origin = argv[++i];
      continue;
    }
    if (token === '--port') {
      result.port = argv[++i];
      continue;
    }
    result._.push(token);
  }

  return result;
}

function parsePort(portValue) {
  if (portValue == null) return 8080;

  const parsed = Number(portValue);
  if (!Number.isInteger(parsed) || parsed < 1 || parsed > 65535) {
    throw new Error(`Invalid port "${portValue}". Expected an integer between 1 and 65535.`);
  }

  return parsed;
}

function printUsage() {
  console.error('Usage: vmblu llm-bridge <provider> [folder] [--origin <url>] [--port <number>] [--force] [--dry-run]');
}

function buildConfig({ provider, origin, port }) {
  return {
    provider,
    mode: 'local-bridge',
    publicBaseUrl: `http://127.0.0.1:${port}/v1`,
    proxy: {
      bindHost: '127.0.0.1',
      port,
      allowedOrigin: origin,
      upstreamBaseUrl: 'https://api.openai.com',
      apiKeyEnv: 'OPENAI_API_KEY',
      allowedPaths: [
        '/v1/responses',
        '/v1/chat/completions',
        '/v1/models'
      ]
    }
  };
}

function buildProxySource() {
  return `import fs from 'fs';
import http from 'http';
import https from 'https';
import { fileURLToPath } from 'url';
import path from 'path';

// Read the local bridge policy generated by vmblu.
const CONFIG_PATH = new URL('./config.json', import.meta.url);
const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
const { provider, proxy, publicBaseUrl } = config;
const BRIDGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

loadDotEnv(path.join(BRIDGE_ROOT, '.env'));
loadDotEnv(path.join(BRIDGE_ROOT, '.env.local'));

// The provider key is kept on the user's machine and injected only here.
const apiKey = () => process.env[proxy.apiKeyEnv];

// Keep the surface area intentionally small and predictable.
const allowedMethods = new Set(['GET', 'POST', 'OPTIONS']);
const allowedPaths = new Set(proxy.allowedPaths || []);

// This server only accepts local requests and forwards approved ones upstream.
const server = http.createServer((req, res) => {
  const origin = String(req.headers.origin || '');

  if (!isAllowedOrigin(origin)) {
    res.writeHead(403, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ error: 'Origin not allowed by local bridge.' }));
    return;
  }

  writeCorsHeaders(res, origin);

  if (!allowedMethods.has(req.method || '')) {
    res.writeHead(405, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ error: 'Method not allowed.' }));
    return;
  }

  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }

  // Validate the local request path before contacting the upstream provider.
  const localUrl = new URL(req.url || '/', \`http://\${proxy.bindHost}:\${proxy.port}\`);
  if (localUrl.pathname === '/health') {
    const status = getBridgeStatus();
    res.writeHead(status.apiKeyConfigured ? 200 : 503, { 'content-type': 'application/json' });
    res.end(JSON.stringify(status));
    return;
  }

  if (!allowedPaths.has(localUrl.pathname)) {
    res.writeHead(404, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ error: 'Path not allowed by local bridge.' }));
    return;
  }

  if (!apiKey()) {
    res.writeHead(503, { 'content-type': 'application/json' });
    res.end(JSON.stringify(getBridgeStatus()));
    return;
  }

  // Forward the request to the provider while adding the local API key.
  const upstreamUrl = new URL(localUrl.pathname + localUrl.search, proxy.upstreamBaseUrl);
  const upstreamReq = https.request(upstreamUrl, {
    method: req.method,
    headers: buildUpstreamHeaders(req.headers, apiKey())
  }, (upstreamRes) => {
    // Preserve the provider response as-is, except for local CORS headers.
    const headers = buildDownstreamHeaders(upstreamRes.headers, origin);
    res.writeHead(upstreamRes.statusCode || 502, headers);
    upstreamRes.pipe(res);
  });

  upstreamReq.on('error', (error) => {
    if (res.headersSent) {
      res.destroy(error);
      return;
    }

    res.writeHead(502, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ error: 'Upstream request failed.', detail: error.message }));
  });

  req.pipe(upstreamReq);
});

server.listen(proxy.port, proxy.bindHost, () => {
  console.log(\`Local \${provider} bridge listening on \${publicBaseUrl}\`);
  console.log(\`Allowed browser origin: \${proxy.allowedOrigin}\`);
  console.log(\`Bridge health endpoint: http://\${proxy.bindHost}:\${proxy.port}/health\`);
  if (proxy.allowedOrigin === 'any') {
    console.warn('Warning: this bridge accepts requests from any browser origin.');
  }
  if (!apiKey()) {
    console.warn(\`Missing \${proxy.apiKeyEnv}. The bridge is up, but requests to the provider will return 503 until the key is configured.\`);
  }
});

function isAllowedOrigin(origin) {
  // Requests without an Origin header are treated as local non-browser calls.
  if (!origin) return true;
  if (proxy.allowedOrigin === 'any') return true;
  return origin === proxy.allowedOrigin;
}

function writeCorsHeaders(res, origin) {
  if (proxy.allowedOrigin === 'any') {
    res.setHeader('Access-Control-Allow-Origin', '*');
  } else if (origin && origin === proxy.allowedOrigin) {
    res.setHeader('Access-Control-Allow-Origin', origin);
  }
  res.setHeader('Vary', 'Origin');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, OpenAI-Beta');
}

function buildUpstreamHeaders(incomingHeaders, apiKeyValue) {
  // Only forward the minimum request headers needed by the provider API.
  const headers = {
    authorization: \`Bearer \${apiKeyValue}\`
  };

  const forwardedHeaders = ['accept', 'content-type', 'content-length', 'openai-beta'];
  for (const name of forwardedHeaders) {
    const value = incomingHeaders[name];
    if (value != null) {
      headers[name] = value;
    }
  }

  return headers;
}

function buildDownstreamHeaders(upstreamHeaders, origin) {
  // Strip hop-by-hop and upstream CORS headers before returning locally.
  const blocked = new Set([
    'access-control-allow-origin',
    'access-control-allow-methods',
    'access-control-allow-headers',
    'connection',
    'keep-alive',
    'proxy-authenticate',
    'proxy-authorization',
    'te',
    'trailers',
    'transfer-encoding',
    'upgrade'
  ]);

  const headers = {};
  for (const [key, value] of Object.entries(upstreamHeaders)) {
    if (blocked.has(key) || value == null) continue;
    headers[key] = value;
  }

  if (proxy.allowedOrigin === 'any') {
    headers['Access-Control-Allow-Origin'] = '*';
  } else if (origin && origin === proxy.allowedOrigin) {
    headers['Access-Control-Allow-Origin'] = origin;
  }
  headers['Vary'] = 'Origin';

  return headers;
}

function getBridgeStatus() {
  return {
    provider,
    mode: config.mode,
    publicBaseUrl,
    healthUrl: \`http://\${proxy.bindHost}:\${proxy.port}/health\`,
    apiKeyEnv: proxy.apiKeyEnv,
    apiKeyConfigured: Boolean(apiKey()),
    allowedOrigin: proxy.allowedOrigin,
    reason: apiKey()
      ? 'Connected to the local LLM bridge.'
      : \`The local bridge is running, but \${proxy.apiKeyEnv} is not configured. Add it to .env.local or the shell before starting the bridge.\`
  };
}

function loadDotEnv(filePath) {
  if (!fs.existsSync(filePath)) return;

  const lines = fs.readFileSync(filePath, 'utf8').split(/\\r?\\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIndex = trimmed.indexOf('=');
    if (eqIndex < 1) continue;

    const key = trimmed.slice(0, eqIndex).trim();
    if (!key) continue;

    let value = trimmed.slice(eqIndex + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    process.env[key] = value;
  }
}
`;
}

function buildReadme({ provider, origin }) {
  return `# Local LLM Bridge

This bridge keeps the provider API key on the user's machine.

Generated provider: ${provider}
Default allowed origin: ${origin}

## What it does

- Listens only on \`127.0.0.1\`
- Accepts browser requests only from the configured origin
- Reads the provider API key from the shell or the project \`.env\` / \`.env.local\`
- If both files define the same variable, \`.env.local\` overrides \`.env\`
- Forwards only an allowlisted set of API paths

## Before first use

1. Review \`proxy.js\` and \`config.json\`.
2. Put \`${provider === 'openai' ? 'OPENAI_API_KEY' : 'API_KEY'}\` in \`.env.local\` for local development, or set it in the shell that launches the bridge.
3. Change \`proxy.allowedOrigin\` if your app is not served from the default local dev origin.
4. If you set \`proxy.allowedOrigin\` to \`"any"\`, treat it as a temporary local-testing shortcut.

Current allowed origin: ${origin}

## Run it

\`\`\`bash
node ./.vmblu/llm-bridge/proxy.js
\`\`\`

If this project has a package.json, the command also adds:

\`\`\`bash
npm run llm-bridge
\`\`\`

The bridge also exposes a local status endpoint:

\`\`\`bash
http://127.0.0.1:8080/health
\`\`\`

It reports whether the bridge is reachable and whether \`${provider === 'openai' ? 'OPENAI_API_KEY' : 'API_KEY'}\` is configured.

## App and MCP configuration

Use \`publicBaseUrl\` from \`config.json\` as the LLM base URL for browser code or a local MCP server when you want both to talk through the same bridge.
`;
}

async function ensureDir(dirPath, dryRun) {
  if (dryRun) {
    console.log(`[dry-run] mkdir -p ${dirPath}`);
    return;
  }

  await fsp.mkdir(dirPath, { recursive: true });
}

async function writeFileSafe(filePath, content, { force, dryRun }) {
  if (fs.existsSync(filePath) && !force) {
    throw new Error(`File exists (use --force to overwrite): ${filePath}`);
  }

  if (dryRun) {
    console.log(`[dry-run] write ${filePath}${force ? ' (force)' : ''}`);
    return;
  }

  await fsp.writeFile(filePath, content, 'utf8');
}

async function addPackageScript(targetDir, { force, dryRun }) {
  const pkgPath = path.join(targetDir, 'package.json');
  if (!fs.existsSync(pkgPath) || !fs.statSync(pkgPath).isFile()) return;

  const raw = await fsp.readFile(pkgPath, 'utf8');
  const pkg = JSON.parse(raw);
  const scripts = pkg.scripts && typeof pkg.scripts === 'object' ? pkg.scripts : {};
  const scriptName = 'llm-bridge';
  const scriptValue = 'node ./.vmblu/llm-bridge/proxy.js';

  if (scripts[scriptName] === scriptValue) return;

  if (scripts[scriptName] && scripts[scriptName] !== scriptValue && !force) {
    console.warn(`Skipping package.json script "${scriptName}" because it already exists. Use --force to replace it.`);
    return;
  }

  const nextPkg = {
    ...pkg,
    scripts: {
      ...scripts,
      [scriptName]: scriptValue
    }
  };

  if (dryRun) {
    console.log(`[dry-run] update ${pkgPath} -> add script "${scriptName}"`);
    return;
  }

  await fsp.writeFile(pkgPath, JSON.stringify(nextPkg, null, 2) + '\n', 'utf8');
}
