// Auto-generated by cli/scripts/generate-schema-version.js
export const RUNTIME_VERSION = "0.10.0";

export function runtimeCompatibilityFamily(version = RUNTIME_VERSION) {
    const match = String(version ?? '').match(/^(\d+)\.(\d+)\.(\d+)(?:[-+].*)?$/)
    if (!match) throw new Error(`Invalid vmblu runtime version: ${version}`)
    return `${match[1]}.${match[2]}`
}

export function assertRuntimeCompatibility(expectedFamily) {
    if (!expectedFamily) return runtimeCompatibilityFamily()
    const actualFamily = runtimeCompatibilityFamily()
    if (expectedFamily !== actualFamily) {
        throw new Error(`Incompatible vmblu runtime ${RUNTIME_VERSION}; generated application requires compatibility family ${expectedFamily}`)
    }
    return actualFamily
}
